#!/bin/bash

# mostly from the archlinux wiki
# I think pacman-mirrors is Manjaro specific though

	echo 'script works';
	sudo pacman-mirrors --fasttrack;
	sudo pacman -Syyu;
	paccache -r;
	paccache -rk1 ;
	paccache -ruk0 ;
	pacman -Sc ;
	pacman -Rns $(pacman -Qtdq);
	pacman -Qqe > ~/.pkglist.txt;
	echo 'errors:';
	systemctl --failed;
	journalctl -p 3 -xb;
