#!/usr/bin/env python

# from https://unix.stackexchange.com/questions/12482/split-pages-in-pdf/12483
# may need adapting for splitting in the right direction

# absolutely not finished, doesn't work

import copy, sys
from pyPdf import PdfFileWriter, PdfFileReader
input = PdfFileReader(sys.stdin)
output = PdfFileWriter()
for p in [input.getPage(i) for i in range(0,input.getNumPages())]:
    q = copy.copy(p)
    (w, h) = p.mediaBox.upperRight
    p.mediaBox.upperRight = (w, h/2)
    q.mediaBox.upperLeft = (w, h/2)
    output.addPage(p)
    output.addPage(q)
output.write(sys.stdout)
