#!/bin/bash

pkill x11vnc
xrandr --output VIRTUAL1 --off && xrandr --delmode VIRTUAL1 "distant" && xrandr && xrandr --rmmode "distant"

killall conky
conky < /dev/null &>/dev/null &
disown 'conky < /dev/null &> /dev/null'
